[package]
name = "fingerprint-driver"
version = "0.1.0"
authors = ["Temirkhan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.6.3"
bytebuffer-rs = "0.3.1"